### ISSUE TITLE
Simulation files have premature line break; throws error

### ISSUE THREAD

**Issue by wolframalexa** [antmicro/gerber2ems#12]
I am running the simulator on your [signal integrity test board](https://github.com/antmicro/signal-integrity-test-board). The simulator has successfully completed the simulation step and throws an error when getting into the postprocessing step, because the simulation files have 1 column in some of the rows. This appears to be because the penultimate row is getting truncated, like so:
```
% time-domain current integration by openEMS v0.0.36-15-g1ccf094 @Fri Aug 23 14:38:22 2024
% start-coordinates: (0.099,-0.0858,-3e-05) m -> [537,1,46]
% stop-coordinates: (0.099,-0.0758,0) m -> [537,3,47]
% t/s	current
3.33932955252e-15	-0
6.24788559276e-12	-1.54775497974e-12
1.2492431856e-11	-1.59316795867e-11
1.87369781192e-11	-6.2975034909e-11
2.49815243824e-11	-1.78341424961e-10
3.12260706456e-11	-4.08827860454e-10
3.74706169088e-11	-7.80109976617e-10
4.3715163172e-11	-1.20430199146e-09
4.99597094352e-11	-1.380123682e-09
5.62042556984e-11	-6.19580997618e-10
6.24488019617e-11	2.12990935999e-09
9e-10
```
I've been fixing this manually by simply deleting the row but I think this is a bad long-term solution. I'm attaching the simulation files for one port in a .zip here: [port_1_errors.zip](https://github.com/user-attachments/files/16733235/port_1_errors.zip).

**Comment by wolframalexa** [comment]
Closing this issue. This behaviour happens when you don't have enough simulation steps.

**Comment by SakuraWutk** [comment]
Nice, I get it.
